"""Cull page: per-day grid of thumbnails with auto-flag pre-checks.

User confirms or unchecks flagged frames; clicking Save writes the confirmed
exclusions to `_mac_meta.json.excluded_images`. The grid reads from `_thumbs/`
(generated by bundle.py at import time) so a 40-frame day ships ~4 MB to the
browser instead of ~80 MB.
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Iterable

import streamlit as st

from growzones import state

try:
    from growzones.auto_cull import auto_cull_day
except ImportError:  # pragma: no cover
    auto_cull_day = None


st.set_page_config(page_title="Cull — GrowZones", layout="wide")

_MAC_META_SCHEMA_VERSION = 1
_GRID_COLS = 4


def _list_day_dirs(captures_dir: Path) -> list[Path]:
    if not captures_dir.exists():
        return []
    days: list[Path] = []
    for child in captures_dir.iterdir():
        if not child.is_dir():
            continue
        try:
            datetime.strptime(child.name, "%Y-%m-%d")
        except ValueError:
            continue
        days.append(child)
    return sorted(days, key=lambda p: p.name)


def _load_meta(day_dir: Path) -> dict:
    meta_path = day_dir / "_mac_meta.json"
    if not meta_path.exists():
        return {
            "schema_version": _MAC_META_SCHEMA_VERSION,
            "tag": None,
            "tag_source": None,
            "excluded_images": [],
            "drift_ssim_vs_prior": None,
        }
    data = json.loads(meta_path.read_text())
    if data.get("schema_version") != _MAC_META_SCHEMA_VERSION:
        raise ValueError(
            f"Unknown _mac_meta.json schema version "
            f"{data.get('schema_version')!r} at {meta_path}"
        )
    return data


def _save_meta(day_dir: Path, meta: dict) -> None:
    meta_path = day_dir / "_mac_meta.json"
    tmp = meta_path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(meta, indent=2))
    tmp.replace(meta_path)


def _load_suggestions(day_dir: Path) -> dict:
    """Read _cull_suggestions.json or return an empty stub."""
    path = day_dir / "_cull_suggestions.json"
    if not path.exists():
        return {"suggestions": [], "threshold": None}
    return json.loads(path.read_text())


def _thumb_or_full(day_dir: Path, image_name: str) -> Path:
    """Prefer the thumbnail; fall back to the full JPEG."""
    thumb = day_dir / "_thumbs" / image_name
    if thumb.exists():
        return thumb
    return day_dir / image_name


def _capture_time(image_name: str) -> str:
    """Extract HH:MM:SS from an `HH-MM-SS.jpg` filename."""
    stem = image_name.rsplit(".", 1)[0]
    parts = stem.split("-")
    if len(parts) != 3:
        return image_name
    return ":".join(parts)


def _run_auto_cull(loc, date: str) -> None:
    """Invoke auto_cull.auto_cull_day under a spinner."""
    if auto_cull_day is None:
        st.info("Auto-cull is coming in a later milestone.")
        return
    try:
        with st.spinner(f"Scoring frames for {date}…"):
            auto_cull_day(loc, date)
    except Exception as e:  # noqa: BLE001
        st.error(f"Auto-cull failed: {e}")
        return
    st.toast("Auto-cull complete")
    st.rerun()


def _render_grid(day_dir: Path, meta: dict, suggestions: dict) -> dict[str, bool]:
    """Render the thumbnail grid; return {image_name: checked_state} per checkbox."""
    suggestion_by_image = {s["image"]: s for s in suggestions.get("suggestions", [])}
    excluded = set(meta.get("excluded_images", []))

    jpegs = sorted(p for p in day_dir.glob("*.jpg") if not p.name.startswith("_"))
    checked: dict[str, bool] = {}

    for row_start in range(0, len(jpegs), _GRID_COLS):
        cols = st.columns(_GRID_COLS)
        for offset, col in enumerate(cols):
            idx = row_start + offset
            if idx >= len(jpegs):
                continue
            jpeg = jpegs[idx]
            name = jpeg.name
            with col:
                st.image(
                    str(_thumb_or_full(day_dir, name)),
                    caption=_capture_time(name),
                    use_container_width=True,
                )
                suggestion = suggestion_by_image.get(name)
                if suggestion is not None:
                    st.caption(f"diff: {suggestion['diff_score']:.1f}")
                default_checked = name in excluded or (
                    suggestion is not None and suggestion.get("flagged", False)
                )
                checked[name] = st.checkbox(
                    "Exclude",
                    value=default_checked,
                    key=f"cull_{day_dir.name}_{name}",
                )
    return checked


def main() -> None:
    state.location_selector_sidebar()
    loc = state.get_current_location()
    st.title(f"Cull — {loc.name}")

    days = _list_day_dirs(loc.captures_dir)
    if not days:
        st.info("No capture days yet. Import a bundle on the Import page.")
        return

    date = st.selectbox(
        "Day",
        options=[d.name for d in days],
        index=len(days) - 1,
        key="cull_day",
    )
    day_dir = loc.captures_dir / date

    action_cols = st.columns([1, 1, 4])
    if action_cols[0].button("Run auto-cull"):
        _run_auto_cull(loc, date)

    meta = _load_meta(day_dir)
    suggestions = _load_suggestions(day_dir)

    if not suggestions.get("suggestions"):
        st.caption(
            "No auto-cull suggestions yet for this day. Click Run auto-cull "
            "to score every frame against the day's median."
        )

    checked = _render_grid(day_dir, meta, suggestions)

    if not checked:
        return

    if st.button("Save exclusions", type="primary"):
        meta["excluded_images"] = sorted(name for name, on in checked.items() if on)
        _save_meta(day_dir, meta)
        st.success(f"Saved {len(meta['excluded_images'])} exclusion(s) for {date}.")
        st.toast("Exclusions saved")


main()
